# Security Policy Database for Prong A

[SYNC]
spp_immediate = 0x01
spp_delayed = 0x01

[DELAY_REQ]
spp_immediate = 0x01
spp_delayed = 0x01

[PDELAY_REQ]
spp_immediate = 0x01
spp_delayed = 0x01

[PDELAY_RESP]
spp_immediate = 0x01
spp_delayed = 0x01

[FOLLOW_UP]
spp_immediate = 0x01
spp_delayed = 0x01

[DELAY_RESP]
spp_immediate = 0x01
spp_delayed = 0x01

[PDELAY_RESP_FOLLOW_UP]
spp_immediate = 0x01
spp_delayed = 0x01

[ANNOUNCE]
spp_immediate = 0x01
spp_delayed = 0x01

[SIGNALING]
spp_immediate = 0x01
spp_delayed = 0x01

[MANAGEMENT]
spp_immediate = 0xFF
spp_delayed = 0xFF
